# Generated by Django 4.1.1 on 2022-10-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
    ]
